[[plugins]]
    package = "@sentry/netlify-build-plugin"

    [plugins.inputs]
        sentryOrg = "helix-dynamics"
        sentryProject = "portfolio-netlify"
        sentryRepository = "Logit-Transporters/logit-potifilo"
        skipSetCommits = false
        deployPreviews = false